name: run app.py

on:
  push:
    branches:
      - main  # Change this if your branch is different

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:   
          python-version: '3.12'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python script
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: python app.py
